# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: backend-integration-tests

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Setup .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      # 3. Restore dependencies
      - name: Restore Application Integration Tests
        run: dotnet restore tests/Application.IntegrationTests/Application.IntegrationTests.csproj

      # 4. Build
      - name: Build Application Integration Tests
        run: dotnet build --no-restore --configuration Release tests/Application.IntegrationTests/Application.IntegrationTests.csproj

      # 5. Run Application Integration Tests
      - name: Run Application Integration Tests
        run: |
          dotnet test tests/Application.IntegrationTests/Application.IntegrationTests.csproj \
            --no-build --configuration Release \
            --logger "trx;LogFileName=application-results.trx"

      # 6. Restore dependencies
      - name: Restore API Integration Tests
        run: dotnet restore tests/API.IntegrationTests/API.IntegrationTests.csproj

      # 7. Build
      - name: Build API Integration Tests
        run: dotnet build --no-restore --configuration Release tests/API.IntegrationTests/API.IntegrationTests.csproj

      # 8. Run API Integration Tests
      - name: Run API Integration Tests
        run: |
          dotnet test tests/API.IntegrationTests/API.IntegrationTests.csproj \
            --no-build --configuration Release \
            --logger "trx;LogFileName=api-results.trx"

      # 9. Publish test results (optional but recommended)
      - name: Publish Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: integration-test-results
          path: '**/*.trx'
